### ISSUE TITLE
make file not working

### ISSUE THREAD

**Issue by djash7777777** [EvanPurkhiser/prolink-overlay#3]
Last login: Mon Mar 12 22:42:54 on ttys000
You have new mail.
MacBook-Pro-de-gontcharouk:~ sacha$ /Users/sacha/Desktop/prolink-overlay-master/Makefile ; exit;
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 1: shell: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 1: VERSION: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 3: go-deps:: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 4: dep: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 6: js-deps:: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 7: cd: overlay: No such file or directory
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 9: deps:: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 11: dist/assets:: No such file or directory
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 13: cd: overlay: No such file or directory
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 15: dist/prolink-overlay-dev:: No such file or directory
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 16: VERSION: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 16: go: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 18: dist/prolink-overlay:: No such file or directory
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 20: rice: command not found
/Users/sacha/Desktop/prolink-overlay-master/Makefile: line 22: .PHONY:: command not found
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]

**Comment by djash7777777** [comment]
hi man ! any issue?

**Comment by djash7777777** [comment]
i m on mac sierra and i use cdj nexus 2

**Comment by EvanPurkhiser** [comment]
You have to run `make` to execute the makefile :)
